### ISSUE TITLE
Fails to build with php 8.2

### ISSUE THREAD

**Issue by wom-bat** [Qihoo360/phptrace#108]
I see:
```
extension/trace.c:104:158: error: expected ';', ',' or ')' before 'TSRMLS_DC'
  104 | static void frame_build(pt_frame_t *frame, zend_bool internal, unsigned char type, zend_execute_data *caller, zend_execute_data *ex, zend_op_array *op_array TSRMLS_DC);
      |                                                                                                                                                              ^~~~~~~~~
```
and similar.
